<?php 

$query = $this->db->query("
	DROP TABLE IF EXISTS `".DB_PREFIX ."mega_menu`
");

$query = $this->db->query("
	CREATE TABLE IF NOT EXISTS `".DB_PREFIX."mega_menu` (
		`id` int(11) unsigned NOT NULL AUTO_INCREMENT,
		`parent_id` int(11) NOT NULL,
		`rang` int(11) NOT NULL,
		`icon` varchar(255) NOT NULL DEFAULT '',
		`name` text,
		`link` text,
		`description` text,
		`new_window` int(11) NOT NULL DEFAULT '0',
		`status` int(11) NOT NULL DEFAULT '0',
		`position` int(11) NOT NULL DEFAULT '0',
		`submenu_width` text,
		`submenu_type` int(11) NOT NULL DEFAULT '0',
		`content_width` int(11) NOT NULL DEFAULT '12',
		`content_type` int(11) NOT NULL DEFAULT '0',
		`content` text,
		PRIMARY KEY (`id`)
	) ENGINE=MyISAM DEFAULT CHARSET=utf8 AUTO_INCREMENT=1
");

$query = $this->db->query("
		INSERT INTO `".DB_PREFIX."mega_menu` (`id`, `parent_id`, `rang`, `icon`, `name`, `link`, `description`, `new_window`, `status`, `position`, `submenu_width`, `submenu_type`, `content_width`, `content_type`, `content`) VALUES
		(1, 0, 1, '', 'a:1:{i:1;s:5:\"Women\";}', 'index.php?route=product/category&path=20', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '700px', 0, 4, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:29:\"&lt;p&gt;&lt;br&gt;&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(2, 0, 4, '', 'a:1:{i:1;s:3:\"Men\";}', 'index.php?route=product/category&path=18', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 12, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:29:\"&lt;p&gt;&lt;br&gt;&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(7, 1, 1, '', 'a:1:{i:1;s:8:\"Clothing\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 4, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:1072:\"&lt;p style=&quot;font-size: 12px;text-transform:uppercase;color:#000000;font-weight: 700;&quot;&gt;Clothing&lt;/p&gt;&lt;p&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;New Arrivals&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Sale&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Clothing&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Trench Coats&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Bags&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Scarves&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Shoes&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Accessories&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Make-up&lt;/a&gt; &lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;New Arrivals&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Sale&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Clothing&lt;/a&gt;&lt;br&gt;&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(8, 1, 2, '', 'a:1:{i:1;s:11:\"Accessories\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 4, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:1057:\"&lt;p style=&quot;font-size: 12px;text-transform:uppercase;color:#000000;font-weight:700;&quot;&gt;Accessories&lt;/p&gt;&lt;p&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Shoes&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Bags&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Belts&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Bracelets&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Ties&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Sunglasses&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Hats&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Leather Goods&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Gloves&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Bags&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Belts&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Bracelets&lt;/a&gt;&lt;br&gt;&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(9, 1, 3, '', 'a:1:{i:1;s:16:\"Featured Product\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 4, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:495:\"&lt;div style=&quot;text-align:center;&quot;&gt;&lt;p style=&quot;font-size: 12px;color:#000000;text-transform:uppercase;font-weight: 700;&quot;&gt;Featured Product&lt;/p&gt;&lt;p style=&quot;padding-top:10px;&quot;&gt;&lt;img alt=&quot;&quot; src=&quot;image/catalog/kingstorepro/featuredproduct.jpg&quot;&gt;&lt;/p&gt;&lt;p&gt;&lt;a href=&quot;#&quot;&gt;Palk Monogram&lt;/a&gt;&lt;/p&gt;&lt;p style=&quot;font-size: 14px; font-weight: 700; color: #000000;&quot;&gt;$2500&lt;/p&gt;&lt;/div&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(10, 2, 6, '', 'a:1:{i:1;s:4:\"Sale\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 2, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:981:\"&lt;p&gt;&lt;a onclick=&quot;index.php?route=product/special&quot; href=&quot;index.php?route=product/special&quot; style=&quot;color:#d63131;text-transform:uppercase;font-weight: 700;&quot;&gt;Sale&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot; style=&quot;color:#000000;font-weight: 700;&quot;&gt;New&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot; style=&quot;color:#000000;font-weight: 700;&quot;&gt;New Collection&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot; style=&quot;color:#000000;font-weight: 700;&quot;&gt;Casual&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot; style=&quot;color:#000000;font-weight: 700;&quot;&gt;Suits&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot; style=&quot;color:#000000;font-weight: 700;&quot;&gt;Blacksmith&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot; style=&quot;color:#000000;font-weight: 700;&quot;&gt;Sport&lt;/a&gt;&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(11, 2, 7, '', 'a:1:{i:1;s:12:\"Clothing Men\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 2, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:1075:\"&lt;p style=&quot;font-size: 12px;color:#000000;text-transform:uppercase;font-weight: 700;&quot;&gt;Clothing&lt;/p&gt;&lt;p&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Coats&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Outerwear&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Blazers&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Leather&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Cardigans and sweaters&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Shirt&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;T-shirts&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Polo shirts&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Pants&lt;/a&gt; &lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Jeans&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Shorts&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Pyjamas&lt;/a&gt;&lt;br&gt;&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(12, 2, 8, '', 'a:1:{i:1;s:11:\"Accessories\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 2, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:927:\"&lt;p style=&quot;font-size: 12px;color:#000000;text-transform:uppercase;font-weight: 700;&quot;&gt;Accessories&lt;/p&gt;&lt;p&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Shoes&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Bags&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Belts&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Leather goods&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Bracelets&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Gloves&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Ties&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Sunglasses&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Hats and caps&lt;/a&gt; &lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Other accessories&lt;/a&gt;&lt;br&gt;&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(13, 2, 9, '', 'a:1:{i:1;s:9:\"Catalogue\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 2, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:803:\"&lt;p style=&quot;font-size: 12px;color:#000000;text-transform:uppercase;font-weight: 700;&quot;&gt;Catalogue&lt;/p&gt;&lt;p&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;Winter 2015&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;2015 Autumn&lt;/a&gt;&lt;br&gt;&lt;/p&gt;&lt;p style=&quot;font-size: 12px;text-transform:uppercase;color:#000000;font-weight: 700;&quot;&gt;Lookbooks&lt;/p&gt;&lt;p&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;2014 December&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;2014 November&lt;/a&gt;&lt;br&gt;&lt;a onclick=&quot;#&quot; href=&quot;#&quot;&gt;2014 August&lt;/a&gt;&lt;br&gt;&lt;/p&gt;&lt;p style=&quot;font-size: 12px;color:#000000;text-transform:uppercase;font-weight: 700;&quot;&gt;The Post&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(14, 2, 10, '', 'a:1:{i:1;s:4:\"Sale\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 4, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:183:\"&lt;a onclick=&quot;index.php?route=product/special&quot; href=&quot;index.php?route=product/special&quot;&gt;&lt;img src=&quot;image/catalog/kingstorepro/sale.jpg&quot;&gt;&lt;/a&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(15, 0, 0, '', 'a:1:{i:1;s:4:\"Home\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 4, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:29:\"&lt;p&gt;&lt;br&gt;&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(4, 0, 5, '', 'a:1:{i:1;s:4:\"Sale\";}', 'index.php?route=product/special', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 4, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:29:\"&lt;p&gt;&lt;br&gt;&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(6, 0, 7, '', 'a:1:{i:1;s:11:\"Information\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '200px', 0, 4, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:29:\"&lt;p&gt;&lt;br&gt;&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(19, 6, 18, '', 'a:1:{i:1;s:5:\"Links\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 12, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:1306:\"&lt;div class=&quot;hover-menu&quot;&gt;\r\n&lt;div class=&quot;menu&quot;&gt;\r\n&lt;ul&gt;\r\n	&lt;li&gt;&lt;a href=&quot;index.php?route=information/information&amp;amp;information_id=4&quot; onclick=&quot;window.location = ''index.php?route=information/information&amp;amp;information_id=4'';&quot;&gt;About us&lt;/a&gt;&lt;/li&gt;\r\n	&lt;li&gt;&lt;a href=&quot;index.php?route=information/information&amp;amp;information_id=6&quot; onclick=&quot;window.location = ''index.php?route=information/information&amp;amp;information_id=6'';&quot;&gt;Delivery Information&lt;/a&gt;&lt;/li&gt;\r\n	&lt;li&gt;&lt;a href=&quot;index.php?route=information/information&amp;amp;information_id=3&quot; onclick=&quot;window.location = ''index.php?route=information/information&amp;amp;information_id=3'';&quot;&gt;Privacy Policy&lt;/a&gt;&lt;/li&gt;\r\n	&lt;li&gt;&lt;a href=&quot;index.php?route=information/information&amp;amp;information_id=5&quot; onclick=&quot;window.location = ''index.php?route=information/information&amp;amp;information_id=5'';&quot;&gt;Terms &amp;amp; Conditions&lt;/a&gt;&lt;/li&gt;\r\n	&lt;li&gt;&lt;a href=&quot;index.php?route=information/contact&quot; onclick=&quot;window.location = ''index.php?route=information/contact'';&quot;&gt;Contact us&lt;/a&gt;&lt;/li&gt;\r\n&lt;/ul&gt;\r\n&lt;/div&gt;\r\n&lt;/div&gt;\r\n\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(5, 0, 6, '', 'a:1:{i:1;s:6:\"Stores\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '800px', 0, 4, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:29:\"&lt;p&gt;&lt;br&gt;&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(16, 5, 13, '', 'a:1:{i:1;s:3:\"Map\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 12, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:230:\"&lt;div style=&quot;text-align:center;&quot;&gt;&lt;p style=&quot;text-align&quot;&gt;&lt;a href=&quot;#&quot;&gt;&lt;img alt=&quot;&quot; src=&quot;image/catalog/kingstorepro/location.jpg&quot;&gt;&lt;/a&gt;&lt;/p&gt;&lt;/div&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(17, 5, 14, '', 'a:1:{i:1;s:7:\"Store 1\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 4, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:334:\"&lt;p&gt;&lt;a href=&quot;#&quot; style=&quot;font-size: 12px;text-transform:uppercase; font-weight: 700;color:#000000;&quot;&gt;KingStore Pro 1&lt;/a&gt;&lt;/p&gt;&lt;p style=&quot;font-size:12px;&quot;&gt;225-235, Oxford Street LONDON&lt;br&gt;&lt;br&gt;020-7534-3505&lt;br&gt;&lt;br&gt;Monday - Sunday 10:45 am - 10:00 pm&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(18, 5, 15, '', 'a:1:{i:1;s:7:\"Store 2\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 4, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:333:\"&lt;p&gt;&lt;a href=&quot;#&quot; style=&quot;font-size: 12px;text-transform:uppercase; font-weight: 700;color:#000000;&quot;&gt;KingStore Pro 1&lt;/a&gt;&lt;/p&gt;&lt;p style=&quot;font-size:12px;&quot;&gt;106-112, Regent Street LONDON&lt;br&gt;&lt;br&gt;207-434-3866&lt;br&gt;&lt;br&gt;Monday - Sunday 10:45 am - 10:00 pm&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(20, 5, 16, '', 'a:1:{i:1;s:7:\"Store 3\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 4, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:326:\"&lt;p&gt;&lt;a href=&quot;#&quot; style=&quot;font-size: 12px;text-transform:uppercase; font-weight: 700;color:#000000;&quot;&gt;KingStore Pro 1&lt;/a&gt;&lt;/p&gt;&lt;p style=&quot;font-size:12px;&quot;&gt;1 Cour de Rome PARIS&lt;br&gt;&lt;br&gt;01-44-53-73-30&lt;br&gt;&lt;br&gt;Monday - Sunday 10:45 am - 10:00 pm&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(22, 0, 5, '', 'a:1:{i:1;s:11:\"Electronics\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '800px', 0, 12, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:29:\"&lt;p&gt;&lt;br&gt;&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(23, 22, 1, '', 'a:1:{i:1;s:23:\"Televisions &amp; Video\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 3, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:654:\"&lt;div style=&quot;text-align:center;&quot;&gt;&lt;p&gt;&lt;a href=&quot;index.php?route=product/category&amp;amp;path=20&quot; onclick=&quot;window.location = &quot;index.php?route=product/category&amp;amp;path=20&quot;;&quot;&gt;&lt;img alt=&quot;&quot; src=&quot;image/catalog/kingstorepro/megamenu1.png&quot;&gt;&lt;/a&gt;&lt;/p&gt;&lt;p&gt;&lt;a href=&quot;index.php?route=product/category&amp;amp;path=20&quot; onclick=&quot;window.location = &quot;index.php?route=product/category&amp;amp;path=20&quot;;&quot; style=&quot;font-size: 12px; font-weight: 400;&quot; target=&quot;_self&quot;&gt;Televisions &amp; Video&lt;/a&gt;&lt;/p&gt;&lt;/div&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(24, 22, 2, '', 'a:1:{i:1;s:29:\"Home Audio &amp; Home Theater\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 3, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:693:\"&lt;div style=&quot;text-align:center;&quot;&gt;&lt;p style=&quot;text-align&quot;&gt;&lt;a href=&quot;index.php?route=product/category&amp;amp;path=18&quot; onclick=&quot;window.location = &quot;index.php?route=product/category&amp;amp;path=18&quot;;&quot;&gt;&lt;img alt=&quot;&quot; src=&quot;image/catalog/kingstorepro/megamenu2.png&quot;&gt;&lt;/a&gt;&lt;/p&gt;&lt;p&gt;&lt;a href=&quot;index.php?route=product/category&amp;amp;path=18&quot; onclick=&quot;window.location = &quot;index.php?route=product/category&amp;amp;path=18&quot;;&quot; style=&quot;font-size: 12px; font-weight: 400;&quot; target=&quot;_self&quot;&gt;Home Audio &amp;amp; Home Theater&lt;/a&gt;&lt;/p&gt;&lt;/div&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(25, 22, 3, '', 'a:1:{i:1;s:15:\"Digital Cameras\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 3, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:675:\"&lt;div style=&quot;text-align:center;&quot;&gt;&lt;p style=&quot;text-align&quot;&gt;&lt;a href=&quot;index.php?route=product/category&amp;amp;path=57&quot; onclick=&quot;window.location = &quot;index.php?route=product/category&amp;amp;path=57&quot;;&quot;&gt;&lt;img alt=&quot;&quot; src=&quot;image/catalog/kingstorepro/megamenu3.png&quot;&gt;&lt;/a&gt;&lt;/p&gt;&lt;p&gt;&lt;a href=&quot;index.php?route=product/category&amp;amp;path=57&quot; onclick=&quot;window.location = &quot;index.php?route=product/category&amp;amp;path=57&quot;;&quot; style=&quot;font-size: 12px; font-weight: 400;&quot; target=&quot;_self&quot;&gt;Digital Cameras&lt;/a&gt;&lt;/p&gt;&lt;/div&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(26, 22, 4, '', 'a:1:{i:1;s:13:\"Video Cameras\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 3, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:673:\"&lt;div style=&quot;text-align:center;&quot;&gt;&lt;p style=&quot;text-align&quot;&gt;&lt;a href=&quot;index.php?route=product/category&amp;amp;path=17&quot; onclick=&quot;window.location = &quot;index.php?route=product/category&amp;amp;path=17&quot;;&quot;&gt;&lt;img alt=&quot;&quot; src=&quot;image/catalog/kingstorepro/megamenu4.png&quot;&gt;&lt;/a&gt;&lt;/p&gt;&lt;p&gt;&lt;a href=&quot;index.php?route=product/category&amp;amp;path=17&quot; onclick=&quot;window.location = &quot;index.php?route=product/category&amp;amp;path=17&quot;;&quot; style=&quot;font-size: 12px; font-weight: 400;&quot; target=&quot;_self&quot;&gt;Video Cameras&lt;/a&gt;&lt;/p&gt;&lt;/div&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(27, 22, 5, '', 'a:1:{i:1;s:14:\"Portable Audio\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 3, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:674:\"&lt;div style=&quot;text-align:center;&quot;&gt;&lt;p style=&quot;text-align&quot;&gt;&lt;a href=&quot;index.php?route=product/category&amp;amp;path=24&quot; onclick=&quot;window.location = &quot;index.php?route=product/category&amp;amp;path=24&quot;;&quot;&gt;&lt;img alt=&quot;&quot; src=&quot;image/catalog/kingstorepro/megamenu5.png&quot;&gt;&lt;/a&gt;&lt;/p&gt;&lt;p&gt;&lt;a href=&quot;index.php?route=product/category&amp;amp;path=24&quot; onclick=&quot;window.location = &quot;index.php?route=product/category&amp;amp;path=24&quot;;&quot; style=&quot;font-size: 12px; font-weight: 400;&quot; target=&quot;_self&quot;&gt;Portable Audio&lt;/a&gt;&lt;/p&gt;&lt;/div&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(28, 22, 6, '', 'a:1:{i:1;s:27:\"Mobile Phones &amp; Tablets\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 3, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:687:\"&lt;div style=&quot;text-align:center;&quot;&gt;&lt;p style=&quot;text-align&quot;&gt;&lt;a href=&quot;index.php?route=product/category&amp;amp;path=34&quot; onclick=&quot;window.location = &quot;index.php?route=product/category&amp;amp;path=34&quot;;&quot;&gt;&lt;img alt=&quot;&quot; src=&quot;image/catalog/kingstorepro/megamenu6.png&quot;&gt;&lt;/a&gt;&lt;/p&gt;&lt;p&gt;&lt;a href=&quot;index.php?route=product/category&amp;amp;path=34&quot; onclick=&quot;window.location = &quot;index.php?route=product/category&amp;amp;path=34&quot;;&quot; style=&quot;font-size: 12px; font-weight: 400;&quot; target=&quot;_self&quot;&gt;Mobile Phones &amp; Tablets&lt;/a&gt;&lt;/p&gt;&lt;/div&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(29, 22, 7, '', 'a:1:{i:1;s:11:\"PlayStation\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 3, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:671:\"&lt;div style=&quot;text-align:center;&quot;&gt;&lt;p style=&quot;text-align&quot;&gt;&lt;a href=&quot;index.php?route=product/category&amp;amp;path=34&quot; onclick=&quot;window.location = &quot;index.php?route=product/category&amp;amp;path=34&quot;;&quot;&gt;&lt;img alt=&quot;&quot; src=&quot;image/catalog/kingstorepro/megamenu7.png&quot;&gt;&lt;/a&gt;&lt;/p&gt;&lt;p&gt;&lt;a href=&quot;index.php?route=product/category&amp;amp;path=34&quot; onclick=&quot;window.location = &quot;index.php?route=product/category&amp;amp;path=34&quot;;&quot; style=&quot;font-size: 12px; font-weight: 400;&quot; target=&quot;_self&quot;&gt;PlayStation&lt;/a&gt;&lt;/p&gt;&lt;/div&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(30, 22, 8, '', 'a:1:{i:1;s:18:\"Business Solutions\";}', '', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 3, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:678:\"&lt;div style=&quot;text-align:center;&quot;&gt;&lt;p style=&quot;text-align&quot;&gt;&lt;a href=&quot;index.php?route=product/category&amp;amp;path=34&quot; onclick=&quot;window.location = &quot;index.php?route=product/category&amp;amp;path=34&quot;;&quot;&gt;&lt;img alt=&quot;&quot; src=&quot;image/catalog/kingstorepro/megamenu8.png&quot;&gt;&lt;/a&gt;&lt;/p&gt;&lt;p&gt;&lt;a href=&quot;index.php?route=product/category&amp;amp;path=34&quot; onclick=&quot;window.location = &quot;index.php?route=product/category&amp;amp;path=34&quot;;&quot; style=&quot;font-size: 12px; font-weight: 400;&quot; target=&quot;_self&quot;&gt;Business Solutions&lt;/a&gt;&lt;/p&gt;&lt;/div&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}'),
		(31, 0, 28, '', 'a:1:{i:1;s:15:\"News &amp; Blog\";}', 'index.php?route=news/ncategory', 'a:1:{i:1;s:0:\"\";}', 0, 0, 0, '100%', 0, 4, 0, 'a:3:{s:4:\"html\";a:1:{s:4:\"text\";a:1:{i:1;s:29:\"&lt;p&gt;&lt;br&gt;&lt;/p&gt;\";}}s:7:\"product\";a:2:{s:2:\"id\";s:0:\"\";s:4:\"name\";s:0:\"\";}s:10:\"categories\";a:4:{s:10:\"categories\";a:0:{}s:7:\"columns\";s:1:\"1\";s:7:\"submenu\";s:1:\"1\";s:15:\"submenu_columns\";s:1:\"1\";}}')
		");
?>





































